version: '3.8'
services:
  # Django app
  backend_notifications:
    container_name: boomslag_ms_notifications
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/app
    ports:
      - 8010:8010
  # Event Queue Kafka
  queue_notifications:
    build: .
    command: >
      sh -c "python consumer.py"