# Generated by Django 3.2.16 on 2023-03-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text_preview',
            field=models.TextField(blank=True),
        ),
    ]
