# Generated by Django 3.2.16 on 2023-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_text_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='course',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order_item',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='thread',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
